allowBuilds:
  '@vscode/vsce-sign': true
  esbuild: true
  nx: true
packages:
  - apps/*
  - packages/*
  - examples/*
linkWorkspacePackages: true
minimumReleaseAgeExclude:
  - typescript
  - '@typescript/*'
  - 'foldkit'
